CREATE TABLE enderecos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  endereco TEXT NOT NULL,
  latitude DECIMAL(10,8) NOT NULL,
  longitude DECIMAL(11,8) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
